const leaderboardMap = new Map()
leaderboardMap.set("Playtime", "minecraft:total_world_time")
leaderboardMap.set("Mob Kills", "minecraft:mob_kills")
leaderboardMap.set("Player Kills", "minecraft:player_kills")
leaderboardMap.set("Damage Dealt", "minecraft:damage_dealt")
leaderboardMap.set("Damage Taken", "minecraft:damage_taken")
leaderboardMap.set("Deaths", "minecraft:deaths")
leaderboardMap.set("Time Alive", "minecraft:time_since_death")
leaderboardMap.set("Distance Crouched", "minecraft:crouch_one_cm")
leaderboardMap.set("Distance Walked", "minecraft:walk_one_cm")
leaderboardMap.set("Distance Sprinted", "minecraft:sprint_one_cm")
leaderboardMap.set("Distance Swum", "minecraft:swim_one_cm")
leaderboardMap.set("Distance Flown", "minecraft:fly_one_cm")
leaderboardMap.set("Distance With Minecart", "minecraft:minecart_one_cm")
leaderboardMap.set("Distance With Boat", "minecraft:boat_one_cm")
leaderboardMap.set("Distance With Pig", "minecraft:pig_one_cm")
leaderboardMap.set("Distance With Horse", "minecraft:horse_one_cm")
leaderboardMap.set("Distance With Strider", "minecraft:strider_one_cm")
leaderboardMap.set("Jumps", "minecraft:jump")
leaderboardMap.set("Fish Caught", "minecraft:fish_caught")
leaderboardMap.set("Animals Bred", "minecraft:animals_bred")
leaderboardMap.set("Cake Slices Eaten", "minecraft:cake_slices_eaten")
leaderboardMap.set("Raid Wins", "minecraft:raid_win")
leaderboardMap.set("Bell Rings", "minecraft:bell_ring")
leaderboardMap.set("Blocks Mined", "minecraft:most_blocks_mined")
leaderboardMap.set("Netherite Mined", "minecraft:most_ancient_debris_mined")


export default leaderboardMap